In [42]:
import pandas as pd
import numpy as np

In [43]:
df =pd.read_excel("C:\\Users\\LENOVO\\Desktop\\Jupyter\\Churn_Unclean_Project.xlsx")

In [44]:
df.head(5)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [45]:
df.shape

(542, 18)

In [46]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    object
 1   Customer_Name          533 non-null    object
 2   Gender                 536 non-null    object
 3   Age                    536 non-null    float64
 4   State                  531 non-null    object
 5   City                   539 non-null    object
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    object
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    object
 11  Payment_Method         526 non-null    object
 12  Internet_Service       535 non-null    object
 13  Tech_Support           530 non-null    object
 14  Senior_Citizen         534 non-null    object
 15  Dependents             539 non-null    object
 16  Churn                  538 non-null    object
 17  Last_Interaction_Date  539 non-null    object
dtypes: float64(4), object(14)
memory usage: 76.3+ KB

In [48]:
df.duplicated().sum()

np.int64(7)

In [49]:
df.drop_duplicates(inplace=True)

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            535 non-null    object
 1   Customer_Name          527 non-null    object
 2   Gender                 530 non-null    object
 3   Age                    529 non-null    float64
 4   State                  525 non-null    object
 5   City                   532 non-null    object
 6   Tenure_Months          528 non-null    float64
 7   Subscription_Type      524 non-null    object
 8   Monthly_Charges        523 non-null    float64
 9   Total_Charges          527 non-null    float64
 10  Contract_Type          532 non-null    object
 11  Payment_Method         520 non-null    object
 12  Internet_Service       529 non-null    object
 13  Tech_Support           524 non-null    object
 14  Senior_Citizen         528 non-null    object
 15  Dependents             533 non-null    object
 16  Churn                  532 non-null    object
 17  Last_Interaction_Date  533 non-null    object
dtypes: float64(4), object(14)
memory usage: 79.4+ KB

In [52]:
df = df.apply(
    lambda x: x.str.strip() if x.dtype == "object" else x
)

In [53]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'City',
       'Tenure_Months', 'Subscription_Type', 'Monthly_Charges',
       'Total_Charges', 'Contract_Type', 'Payment_Method', 'Internet_Service',
       'Tech_Support', 'Senior_Citizen', 'Dependents', 'Churn',
       'Last_Interaction_Date'],
      dtype='object')

In [54]:
cols=["Customer_Name","Gender","State","City","Subscription_Type","Payment_Method","Contract_Type","Internet_Service","Churn","Dependents","Senior_Citizen","Tech_Support"]
for i in cols:
    df[i]=df[i].str.title()

In [55]:
df.head(5)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,Dsl,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,Upi,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [56]:
df.replace(["NaN","N/A",""," "],np.nan,inplace=True)

In [57]:
df["Churn"].value_counts()

Churn
No     405
Yes    127
Name: count, dtype: int64

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            535 non-null    object
 1   Customer_Name          527 non-null    object
 2   Gender                 530 non-null    object
 3   Age                    529 non-null    float64
 4   State                  525 non-null    object
 5   City                   530 non-null    object
 6   Tenure_Months          528 non-null    float64
 7   Subscription_Type      524 non-null    object
 8   Monthly_Charges        523 non-null    float64
 9   Total_Charges          527 non-null    float64
 10  Contract_Type          532 non-null    object
 11  Payment_Method         520 non-null    object
 12  Internet_Service       529 non-null    object
 13  Tech_Support           524 non-null    object
 14  Senior_Citizen         528 non-null    object
 15  Dependents             533 non-null    object
 16  Churn                  532 non-null    object
 17  Last_Interaction_Date  533 non-null    object
dtypes: float64(4), object(14)
memory usage: 79.4+ KB

In [59]:
cols=["Age","Tenure_Months","Monthly_Charges","Total_Charges"]
for i in cols:
    df[i]=pd.to_numeric(df[i],errors="coerce")

In [60]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [61]:

df = df[(df["Age"]>=18) &(df["Age"]<=100)]
# remove negative values
df = df[df["Monthly_Charges"]>=0]
df = df[df["Total_Charges"]>=0]

In [62]:
df.isnull().sum()

Customer_ID               0
Customer_Name             5
Gender                    4
Age                       0
State                     7
City                      5
Tenure_Months             5
Subscription_Type         6
Monthly_Charges           0
Total_Charges             0
Contract_Type             2
Payment_Method           15
Internet_Service          6
Tech_Support              9
Senior_Citizen            6
Dependents                1
Churn                     2
Last_Interaction_Date     2
dtype: int64

In [63]:
df["Customer_value"]=df["Monthly_Charges"]*df["Tenure_Months"]

In [64]:
df.head(2)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,12-10-2025,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026,7215.39

In [65]:
df["Monthly_Revenue"]=df["Monthly_Charges"]

In [66]:
#Tenure grouping "0-12" "13-24" "25-48" "49-72"
bins =[0,12,24,48,72]
labels =["0-12 month","13-24 month","25-48 month","49-72 month"]
df["Tenure_group"]=pd.cut(df["Tenure_Months"],bins=bins,labels=labels)

In [67]:
df["Senior_Flag"]=np.where(df["Age"]>=60,"Senior","Adult")

In [68]:
df["Churn_flag"]=df["Churn"].map({"Yes":1,"No":0})

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    object
 1   Customer_Name          487 non-null    object
 2   Gender                 488 non-null    object
 3   Age                    492 non-null    float64
 4   State                  485 non-null    object
 5   City                   487 non-null    object
 6   Tenure_Months          487 non-null    float64
 7   Subscription_Type      486 non-null    object
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    object
 11  Payment_Method         477 non-null    object
 12  Internet_Service       486 non-null    object
 13  Tech_Support           483 non-null    object
 14  Senior_Citizen         486 non-null    object
 15  Dependents             491 non-null    object
 16  Churn                  490 non-null    object
 17  Last_Interaction_Date  490 non-null    object
 18  Customer_value         487 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_group           487 non-null    category
 21  Senior_Flag            492 non-null    object
 22  Churn_flag             490 non-null    float64
dtypes: category(1), float64(7), object(15)
memory usage: 89.1+ KB

In [70]:
df.isnull().sum()

Customer_ID               0
Customer_Name             5
Gender                    4
Age                       0
State                     7
City                      5
Tenure_Months             5
Subscription_Type         6
Monthly_Charges           0
Total_Charges             0
Contract_Type             2
Payment_Method           15
Internet_Service          6
Tech_Support              9
Senior_Citizen            6
Dependents                1
Churn                     2
Last_Interaction_Date     2
Customer_value            5
Monthly_Revenue           0
Tenure_group              5
Senior_Flag               0
Churn_flag                2
dtype: int64

In [72]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     170
Standard    162
Basic       154
Name: count, dtype: int64

In [73]:
df.loc[df["Subscription_Type"].isna(),["Customer_ID", "Subscription_Type", "Churn", "Churn_flag"]]

    Customer_ID Subscription_Type Churn  Churn_flag
25        C1025               NaN    No         0.0
56        C1056               NaN    No         0.0
72        C1072               NaN   Yes         1.0
143       C1143               NaN    No         0.0
179       C1179               NaN    No         0.0
238       C1238               NaN    No         0.0

In [74]:
print(df.loc[df["Subscription_Type"].isna(), "Churn"].value_counts(dropna=False))

Churn
No     5
Yes    1
Name: count, dtype: int64

In [75]:
df.to_excel("Customer_Churn_Cleaned.xlsx", index=False)